server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: tenant-service
          uri: lb://tenant-service
          predicates:
            - Path=/api/tenants/**
          filters:
            - StripPrefix=2
        - id: ledger-service
          uri: lb://ledger-service
          predicates:
            - Path=/api/ledger/**
          filters:
            - StripPrefix=2
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8082/api/auth/.well-known/jwks.json
  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
